#### Question 1 :- Write a function so that the columns of the output matrix are powers of the input vector. 
 
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
 
 
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde. 

In [1]:
import numpy as np

a = np.array([4,5,6,7,8])
n = 4
vec = [a**(n-i-1) for i in range(n)]
print (vec)
mat = np.column_stack(vec)
print (mat)

[array([ 64, 125, 216, 343, 512], dtype=int32), array([16, 25, 36, 49, 64], dtype=int32), array([4, 5, 6, 7, 8], dtype=int32), array([1, 1, 1, 1, 1], dtype=int32)]
[[ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]
 [343  49   7   1]
 [512  64   8   1]]


In [2]:
a = np.array([4,5,6,7,8])
n = 4

mat1 = np.vander(a,n,increasing=False)
print (mat1)

[[ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]
 [343  49   7   1]
 [512  64   8   1]]


#### Question: Write a function to find moving average in an array over a window:          
        
        Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [3]:
def get_moving_avg (inp,window):
    inp_len = len(inp) # n
    mov_seq = inp_len-window+1 # moving sequence n-k+1; window - k
    return [round(np.sum(inp[val:val+window])/window,2) for val in range(mov_seq)]   

In [4]:
inp = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
output = get_moving_avg(inp,3)
print (output)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
